# Site settings
title: Artjom Svjatickis
description: 'Software Engineer'
url: 'http://anatomij.github.io/anatomij/'
baseurl: '/profile/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Artjom Svjatickis'
  email: artjom.svjatickis@gmail.com
  github_username:  anatomij
  linkedin_username: 

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
